CREATE TABLE "employees" (
	"id" serial PRIMARY KEY NOT NULL,
	"full_name" text NOT NULL,
	"cpf" varchar(14) NOT NULL,
	"rg" varchar(20),
	"birth_date" varchar(10),
	"phone" varchar(15),
	"email" text,
	"address" text,
	"cep" varchar(9),
	"city" text,
	"state" varchar(2),
	"neighborhood" text,
	"contract_role" text NOT NULL,
	"admission_date" varchar(10) NOT NULL,
	"base_salary" varchar(20),
	"total_salary" varchar(20),
	"daily_value" varchar(20),
	"payment_method" text,
	"pix_key" text,
	"bank_details" text,
	"aso_doc_url" text,
	"contract_doc_url" text,
	"identity_doc_url" text,
	"observations" text,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "employees_cpf_unique" UNIQUE("cpf")
);
